# Generated by Django 3.1 on 2020-08-29 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='', max_length=128, verbose_name='昵称')),
                ('bio', models.CharField(default='', max_length=483, verbose_name='个人简介')),
                ('gender', models.CharField(default='未知', max_length=4, verbose_name='性别')),
                ('website', models.CharField(default='', max_length=128, verbose_name='个人网站')),
                ('github', models.CharField(default='', max_length=48, verbose_name='Github')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='角色名称')),
                ('user', models.ManyToManyField(to='id.UserProfile')),
            ],
        ),
    ]
