# Generated by Django 3.1 on 2020-08-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(default='无', max_length=48, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(default='无', max_length=128, verbose_name='个人网站'),
        ),
    ]
