# Generated by Django 3.1 on 2020-08-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_auto_20200829_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='这个人很懒, 什么也没有写.', max_length=483, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='角色名称'),
        ),
    ]
