# Generated by Django 3.1 on 2020-08-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0005_auto_20200829_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
