# Generated by Django 3.1 on 2020-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0006_auto_20200830_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
